Modulo 1 Meteo API
AGrandeC/zrive-ds pull request #1
Opened 2024-01-22 12:34 UTC by AGrandeC

@guillerbf @gsantam

Para realizar la tarea he creado 5 funciones que van anidadas

connect_to_api: se conecta a cualquier API
get_data_meteo_api: se conecta específcamente a la API de meteo proporcionada y devuelve un df con todos los datos para una determinada ciudad. También guarda los datos como CSV para evitar llamar continuamenete a la API
calculate_meteo_mean_max_min_values: la API devuelve para cada variable solicitada una columna por modelo de medición. Para unificar las datos he cogido como valores de referencia la media de todos los modelos y las mediciones máximas y mínimas de todos los modelos
process_data_meteo: agrupa los datos diarios de forma anual para visualizarlos mejor. Para mi tenía más sentido una representación mensual pero se veía muy mal para tantos años
plot_meteo_variables: hace un plot en el que enseña valor medio anual, máximo y mínimo de todas las ciudades y variables
Los test unitarios no me ha dado tiempo a hacerlos.

Ejemplo de plots para Madrid:

![image](https://github.com/AGrandeC/zrive-ds/assets/72738232/574fa978-066d-43d4-8801-ce9f5049ad05)

![image](https://github.com/AGrandeC/zrive-ds/assets/72738232/3c08d3de-fd87-4f2d-b50b-898809d10b70)

![image](https://github.com/AGrandeC/zrive-ds/assets/72738232/afaa2d3f-0d66-4b10-bccc-f185b96bee7f)

2024-01-22 20:01 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +# if __name__ == "__main__":
you should include this in anyscript that is intended to be run standalone: https://stackoverflow.com/questions/419163/what-does-if-name-main-do
so uncomment it. It's normally added at the end of the script

2024-01-22 20:02 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +def connect_to_api(url, method="GET", headers=None, params=None, data=None):
what's the point of adding `None` as default here when obviously the request won't work with it?

2024-01-22 20:04 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +            # Extract the Retry-After header and sleep for that duration
how do you know the retry_after is gonna be there? If it's not this will fail

2024-01-22 20:05 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +            # Extract the Retry-After header and sleep for that duration
Also normally one retries for some number of attemps while you only retry for 1

2024-01-22 20:06 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    except requests.exceptions.HTTPError as errh:
I don't see the point of excepting any Error that the requests library may raise, specially if you are not doing anything special, you are just printing

2024-01-22 20:07 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    API_URL = "https://climate-api.open-meteo.com/v1/climate?"
I'd put this as a global variable, on the top of the script

2024-01-22 20:07 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    COORDINATES = {
Same as before

2024-01-22 20:09 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    except requests.exceptions.ConnectionError as errc:
Also, you are not returning anything in this excepts, meaning that the function will return `None` and therefore your code will break later (which is what you want to avoid with the `except`s)

2024-01-22 20:10 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    data = response.json()
your code will break here if response is `None`. I'd do the `json` in `connect_to_api`

2024-01-22 20:11 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    for column in columns_df:
you can create a data frame directly from a `dict` (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html) no need to do this

2024-01-22 20:14 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +cities = ["Madrid", "London", "Rio"]
put this on top of the script, not here

2024-01-22 20:14 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +VARIABLES = ["temperature_2m_mean", "precipitation_sum", "soil_moisture_0_to_10cm_mean"]
same

2024-01-22 20:15 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +plot_meteo_variables(cities, VARIABLES)
what is the goal of passing `VARIABLES` if this is a constant?

2024-01-22 20:16 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +            x = df["time"].astype(str).values
instead of creating new variables, create new columns on the data frame (`df["y_mean"] = df[var + "_avg"]`)

2024-01-22 20:16 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +            plt.figure(figsize=(16, 10), dpi=80)
create a function to plot

2024-01-22 20:18 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +        data_path = f"{os.getcwd()}/data/{str.lower(city)}_climate.csv"
you are using this same path in multiple functions. It's better to create an function `def get_data_path()` instead

2024-01-22 20:24 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +        columns_var = [col for col in df_meteo.columns if var in col]
I am a little bit confused about this, what are your columns and why `var` can be in more than one column?

2024-01-22 20:25 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +        df_meteo = pd.concat([df_meteo, df_join], axis=1)
In general it's better to use something else like `merge` if you can avoid `pd.concat`. Also, can `df_meteo` and `df_join` have different number of rows?

2024-01-22 20:25 UTC, gsantam commented on src/module_1/module_1_meteo_api.py
> +    columns_final = ["time", "city"] + [
this sounds like a bad idea, I would use rename https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html

2024-01-22 20:26 UTC, gsantam requested changes
Not bad for being the first assignment. Comments on multiple things. Try to add some tests

2024-01-27 10:51 UTC, AGrandeC commented
Got it, thanks for the comments! Will take them into account for future submissions

2024-01-27 10:52 UTC, merged